# Generated by Django 5.2.17 on 2026-09-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_session'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('hall', 'row', 'number'), name='unique_seat_in_hall'),
        ),
    ]
