# Generated by Django 5.2.17 on 2026-09-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_seat_unique_seat_in_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('NORMAL', 'Обычное'), ('VIP', 'VIP'), ('DISABLED', 'Недоступное')], default='NORMAL', max_length=10),
        ),
    ]
