# Generated by Django 5.2.17 on 2026-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_seat_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hall',
            name='vip_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
