# Generated by Django 5.2.17 on 2026-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_hall_standard_price_hall_vip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
